Controller/NavbarController.php
README.md

 fail safe event handling for empty user

---

Resources/translations/AdminLTEBundle.it.xliff

Adds italian translation

---

Resources/docs/sidebar_user.md

Fix YAML syntax

---

Resources/translations/AdminLTEBundle.cs.xliff

Added czech translation

---

Resources/views/Partials/_flash_messages.html.twig

fix flashmessages if no session is available

---

Resources/docs/fos_userbundle.md

updated FOSUserBundle documentation

---

Controller/BreadcrumbController.php
Resources/docs/breadcrumbs.md
Resources/views/Breadcrumb/breadcrumb.html.twig
Resources/views/layout/default-layout.html.twig

- removed title from breadcrumb
- translate breadcrumb items
- updated breadcrumb docu

translate breadcrumb

---

README.md
Resources/docs/breadcrumbs.md
Resources/docs/component_events.md
Resources/docs/configurations.md
Resources/docs/extend_webpack_encore.md
Resources/docs/form_theme.md
Resources/docs/frontend_assets.md
Resources/docs/navbar_messages.md
Resources/docs/navbar_notifications.md
Resources/docs/navbar_tasks.md
Resources/docs/navbar_user.md
Resources/docs/sidebar_navigation.md
Resources/docs/sidebar_user.md

massive documentation update

---

Resources/translations/AdminLTEBundle.ru.xliff

updated russian translation

---

Helper/Constants.php
Model/NotificationModel.php
Model/TaskModel.php
Resources/translations/AdminLTEBundle.cs.xliff
Resources/translations/AdminLTEBundle.de.xliff
Resources/translations/AdminLTEBundle.en.xliff
Resources/translations/AdminLTEBundle.it.xliff
Resources/translations/AdminLTEBundle.ru.xliff
Resources/views/Navbar/messages.html.twig
Resources/views/Navbar/notifications.html.twig
Resources/views/Navbar/tasks.html.twig
Resources/views/Navbar/user.html.twig
Twig/AdminExtension.php

- added missing translations
- template cleanup and unified translations
- new twig filter for text-type css class
- new constants interface

Navbar enhancements

---

Model/MessageModel.php
Model/NotificationModel.php
Model/TaskModel.php
Model/UserModel.php
Resources/docs/breadcrumbs.md
Resources/docs/navbar_messages.md
Resources/docs/navbar_notifications.md
Resources/docs/navbar_tasks.md
Resources/docs/navbar_user.md
Resources/docs/sidebar_navigation.md
Resources/docs/sidebar_user.md
Tests/Model/MessageModelTest.php
Tests/Model/NotificationModelTest.php
Tests/Model/TaskModelTest.php
Tests/Model/UserModelTest.php

- added php-unit tests for all models
- added `getId()` and `setID()` on all models
- support explicit id in all models `getIdentifier()` method
Fixes #28

added setId() and getId() for all models

---

Resources/translations/AdminLTEBundle.cs.xliff

Hey,
I updated some czech translations to be grammatically correct and to be more suitable to the context. I also translated all non-translated strings.
Please check syntax of translations using pluralization :).

Update czech translation

---

Resources/translations/AdminLTEBundle.ar.xliff
composer.json

thanks to Ibrahim Zada for the translations

added arabic translation

---

DependencyInjection/AdminLTEExtension.php
Menu/MenuBuilder.php
README.md
Resources/config/container/knp-menu.yml
Resources/docs/knp_menu.md
Resources/docs/sidebar_navigation.md
Resources/docs/sidebar_user.md
Resources/views/Sidebar/knp-menu.html.twig

fixed support for KNP Menu

---

DependencyInjection/Compiler/TwigPass.php
Resources/docs/form_theme.md
Resources/translations/AdminLTEBundle.de.xliff
Resources/translations/AdminLTEBundle.en.xliff
Resources/views/layout/form-theme.html.twig

- fix agressive form themeing, allow to set application wide theme
- added icons to form widget types: tel, url, email, datetime, password
- add missing translation for required form field - fixes #42

Improved form theming

---

Resources/docs/knp_menu.md
Resources/views/Breadcrumb/knp-breadcrumb.html.twig

fixed breadcrumb support for KnpMenu

---

Twig/AdminExtension.php

use twig namespaces

---

Resources/views/Breadcrumb/knp-breadcrumb.html.twig

Fix filter spaceless behaviour

---

Resources/docs/twig_widgets.md

Wrong default value and config parameter name. 
I'm not sure if the default value of true is really intended.

Small fixes in Widgets documentation for footer

---

Resources/translations/AdminLTEBundle.pt_BR.xliff

added brazilian portuguese translation

---

Resources/translations/AdminLTEBundle.pt_BR.xliff

fix portuguese tag

---

README.md
Resources/translations/AdminLTEBundle.sv.xliff

added swedish translation - thanks tellustheguru

---

Resources/translations/AdminLTEBundle.ja.xliff

This commit is on improving japanese translation with great appreciation to: @magiruuvelvet
Referrence: kevinpapst/kimai2#774 (comment)

Update Japanese translation

---

Resources/translations/AdminLTEBundle.es.xliff

Added the Spanichs translatation

ES translation added

---

README.md
Resources/translations/AdminLTEBundle.nl.xliff

NL translation added

---

README.md
Resources/translations/AdminLTEBundle.fr.xliff

Add french translation

---

Resources/translations/AdminLTEBundle.fi.xliff

Add Finnish language translation.

Add Finnish translation

---

README.md
Resources/translations/AdminLTEBundle.tr.xliff

Turkish language support

---

package.json

Updating Font Awesome package and providing less strict requirement. Resolve #94

Bump Font Awesome version

---

README.md
Resources/translations/AdminLTEBundle.da.xliff

Added danish translations and updated `README.md` to reflect this.

Danish translations

---

README.md
Resources/translations/AdminLTEBundle.zh_CN.xliff

added chinese translations

---

DependencyInjection/AdminLTEExtension.php
DependencyInjection/Configuration.php
Resources/docs/configurations.md
Resources/docs/form_theme.md
Tests/DependencyInjection/ConfigurationTest.php

allow to configure or deactivate form theme

---

Resources/docs/twig_widgets.md
Resources/views/Widgets/box-widget.html.twig

- New blocks for box widget
- Support forms in box_footer

New blocks for box widget

---

Resources/translations/AdminLTEBundle.eu.xliff

Adding Basque language translation

Basque language translation

---

README.md
Resources/translations/AdminLTEBundle.sk.xliff

added slovakian translations

---

Resources/translations/AdminLTEBundle.pl.xliff

A clear and concise description of what this pull request adds or changes.

Polish Language translation

---

README.md
Resources/translations/AdminLTEBundle.eo.xliff

Esperanto translation of AdminLTEBundle. Translated by Sofia Zaretskaia, reviewed by Michal Matúšov for E@I.

Esperanto translation

---

Resources/docs/navbar_tasks.md

A clear and concise description of what this pull request adds or changes.

change 'user' to 'task'

---

README.md
Resources/translations/AdminLTEBundle.he.xliff

added hebrew translations

---

README.md
Resources/translations/AdminLTEBundle.ro.xliff

added romanian translations

---

.github/workflows/linting.yaml
README.md
composer.json

- use matrix of php versions for testing
- relax required php version (allows PHP 8)
- document latest requirements

test on different php versions
